### ISSUE TITLE
Hope Clean Mac Expired OpenMethod

### ISSUE THREAD

**Issue by ManonLoki** [pretty-clean/bugs#17]
<img width="458" alt="image" src="https://user-images.githubusercontent.com/10202538/219586888-111e0f0c-93c1-41c6-a1d6-c5356fcd399d.png">

Script:

/System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/LaunchServices.framework/Versions/A/Support/lsregister -kill -r -domain local -domain user;killall Finder;echo "Open With has been rebuilt, Finder will relaunch"

**Comment by aiyanbo** [comment]
Released in 0.1.36 as an actin.
