### ISSUE TITLE
there is no way to open the application's file path in finder.  

### ISSUE THREAD

**Issue by Nat30** [pretty-clean/bugs#19]
![image](https://github.com/pretty-clean/bugs/assets/26952349/fddfd092-665e-446d-b664-50b27ffc5e54)
i couldn't open the file path in finder very quickly in pretty-clean.

anyway, lots of thanks to you.

**Comment by muescha** [comment]
I have the same: I see `JetBrains 54GB` - but I would like to check what exactly is deleted when I check the JetBrains Checkbox.
Same with Homebrew and other folders

**Comment by aiyanbo** [comment]
@muescha @Nat30 We released 0.1.39, Please upgrade it.

**Comment by muescha** [comment]
Thanks! A magnifying glass icon appears when you hover over an entry.
