### ISSUE TITLE
希望新版本能够将列表的内容按照大小由大到小排序

### ISSUE THREAD

**Issue by ePingTu** [pretty-clean/bugs#2]
❶ 这个在0.1.18这个版本里是这个逻辑，新版本希望也能够这样。
❷ 或者新增排序选项？！

当前使用的是：0.1.20 M1/M2

**Comment by aiyanbo** [comment]
1. 类型列表与文件目录列表都会以大小排序，这个问题会在下一个版本中实现。
2. 先不会新增其他排序方式，PrettyClean 希望用户以最少的操作与时间完成清理。

@ePingTu 你觉得类型列表用什么样的排序方式更为合理？

**Comment by ePingTu** [comment]
缓存类型到没必要按照大小来排列，现在的排列已经是合适的，肯定是从系统到用户。
❶列表内容暂时不动，但里面的缓存数据按照从大到小排序；
❷系统类缓存没必要默认选择状态，让用户不用考量就清除的肯定是应用类缓存；
❸还是有必要加入目录忽略清单（白名单），譬如我个人就有大量使用Books的习惯，部分电子书块头较大，加载电子书会生成大量的缓存，一旦清掉，下次点开一本大体积书籍的话，又要等待好久才能缓存完毕。

**Comment by aiyanbo** [comment]
@ePingTu ignore list (百名单)，dark mode 等计划放在 0.2.x 版本里面实现。0.2.x 版本会在今年年底之前发布。

**Comment by aiyanbo** [comment]
https://github.com/pretty-clean/bugs/issues/3
