### ISSUE TITLE
macos14 dark mode not work

### ISSUE THREAD

**Issue by demon471** [pretty-clean/bugs#20]
upgrade macos 14.0 then app's dark mode is not work fine

**Comment by aiyanbo** [comment]
Please upgrade to 0.1.38

Or you can download it at [https://www.prettyclean.cc/download](https://www.prettyclean.cc/download)

**Comment by demon471** [comment]
already upgrade to 0.1.38 with macos14.0,but don't work 
<img width="481" alt="image" src="https://github.com/pretty-clean/bugs/assets/12760215/004ffa3f-41aa-43ef-b54f-3a04b70686f9">

**Comment by aiyanbo** [comment]
I can't reproduce it on my local machine, can you help get a screenshot?

**Comment by demon471** [comment]
here you are
<img width="1484" alt="image" src="https://github.com/pretty-clean/bugs/assets/12760215/fa20fae9-5ece-499c-9beb-e4a4d8086d9c">

**Comment by aiyanbo** [comment]
@demon471 Thanks, Can we communicate via WeChat? You can send the account number to my email [yanbo.ai@gmail.com](mailto:yanbo.ai@gmail.com).

**Comment by caasols** [comment]
I've been experiencing this for a while as well.

<img width="1800" alt="SCR-20231109-auk-2" src="https://github.com/pretty-clean/bugs/assets/62610736/b4694247-ef2b-47b6-a327-7d5685487f72">

**Comment by aiyanbo** [comment]
@caasols Yes, we have disabled the dark mode in the latest version. The dark mode is being redesigned.
